global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#GitHub'
